name = "ikea-circularity-scraper"
main = "dist/ikea-scraper.js"
account_id = "c7270a21371c405199b38c2ffb7d0420"
compatibility_date = "2025-12-15"
node_compat = true

[vars]
SCRAPER_STORE_DELAY_MS = "1000"
SCRAPER_CATEGORY_DELAY_MS = "500"
SCRAPER_PRODUCT_DELAY_MS = "500"
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_WEBHOOK_URL = ""
NOTIFICATIONS_ENABLED = "true"
NODE_ENV = "production"
FIREBASE_PROJECT_ID = ""
FIREBASE_SERVICE_ACCOUNT = ""
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_CDA_TOKEN = ""
CONTENTFUL_ENVIRONMENT = ""
PORT = "3000"

[triggers]
crons = ["15 8-20 * * *"]

