name = "ikea-circularity-bot"
main = "dist/main.js"
account_id = "c7270a21371c405199b38c2ffb7d0420"
compatibility_date = "2025-12-15"
node_compat = true

[vars]
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_WEBHOOK_URL = ""
NOTIFICATIONS_ENABLED = "true"
NODE_ENV = "production"
FIREBASE_PROJECT_ID = ""
FIREBASE_SERVICE_ACCOUNT = ""
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_CDA_TOKEN = ""
CONTENTFUL_ENVIRONMENT = ""
PORT = "3000"
CLEAR_PREFS_ON_UNSUBSCRIBE = "true"